import assert from 'node:assert/strict';
const base = process.env.API_URL ?? 'http://127.0.0.1:5080';
const suffix = Date.now();
let checks = 0;
async function request(path, { method = 'GET', body, cookie, expected = 200, header = true } = {}) {
  const response = await fetch(base + '/api' + path, { method, headers: { 'Content-Type': 'application/json', ...(header ? { 'X-PutMeOn-Request': '1' } : {}), ...(cookie ? { Cookie: cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const text = await response.text();
  assert.equal(response.status, expected, `${method} ${path}: ${response.status} ${text}`); checks++;
  return { data: text ? JSON.parse(text) : undefined, cookie: response.headers.get('set-cookie')?.split(';')[0] };
}
async function register(label) {
  const email = `${label}-${suffix}@example.com`;
  const { data } = await request('/auth/code', { method: 'POST', body: { email } });
  assert.match(data.developmentCode, /^\d{6}$/); checks++;
  await request('/auth/code', { method: 'POST', body: { email }, expected: 429 });
  const { cookie } = await request('/auth/verify', { method: 'POST', body: { email, code: data.developmentCode }, expected: 204 });
  assert.ok(cookie); checks++;
  await request('/auth/verify', { method: 'POST', body: { email, code: data.developmentCode }, expected: 400 });
  const initial = (await request('/state', { cookie })).data;
  assert.equal(initial.email, email); assert.equal(initial.user, null); checks++;
  await request('/profile', { method: 'PUT', cookie, expected: 204, body: { name: label, phone: '0400000000', trade: 'Carpenter', location: 'Brisbane', companyName: 'Test Company' } });
  const state = (await request('/state', { cookie })).data;
  assert.equal(state.user.name, label); checks++;
  return { email, cookie, id: state.user.id };
}
await request('/health');
await request('/posts', { method: 'POST', body: {}, header: false, expected: 403 });
const owner = await register('owner'); const applicant = await register('applicant');
const date = new Date(Date.now() + 10 * 3600000).toISOString().slice(0,10);
const end = new Date(Date.now() + 7 * 86400000).toISOString().slice(0,10);
const draft = { kind: 'looking', trade: 'Carpenter', location: 'Brisbane South', companyName: 'Owner Company', rate: 55, from: date, to: end, description: 'Local API integration test' };
await request('/posts', { method: 'POST', body: draft, expected: 401 });
await request('/posts', { method: 'POST', cookie: owner.cookie, body: { ...draft, from:'2027-02-30', to:'2027-03-01' }, expected: 400 });
const { data: created } = await request('/posts', { method: 'POST', cookie: owner.cookie, body: draft });
const id = created.id;
const first = (await request(`/state?postId=${id}`, { cookie: owner.cookie })).data.posts[0];
assert.ok(Math.abs(Date.now() - Date.parse(first.createdAt)) < 10000); checks++;
await request(`/posts/${id}`, { method: 'DELETE', cookie: applicant.cookie, expected: 403 });
await request(`/posts/${id}/interest`, { method: 'POST', cookie: owner.cookie, expected: 400 });
await request(`/posts/${id}/interest`, { method: 'POST', cookie: applicant.cookie, expected: 204 });
await request(`/posts/${id}/interest`, { method: 'POST', cookie: applicant.cookie, expected: 204 });
const mine = (await request(`/state?postId=${id}`, { cookie: owner.cookie })).data;
assert.deepEqual(mine.posts[0].interested, [applicant.id]); checks++;
const publicState = (await request(`/state?postId=${id}`, { cookie: applicant.cookie })).data;
assert.equal(publicState.profiles.find(p => p.id === owner.id).phone, ''); assert.equal(publicState.profiles.find(p => p.id === owner.id).email, ''); checks++;
await request(`/posts/${id}/contacts/${owner.id}`, { cookie: applicant.cookie, expected: 403 });
const contact = (await request(`/posts/${id}/contacts/${applicant.id}`, { cookie: owner.cookie })).data;
assert.equal(contact.email, applicant.email); checks++;
await request(`/posts/${id}`, { method: 'PUT', cookie: owner.cookie, body: { ...draft, revision: first.revision }, expected: 409 });
await request(`/posts/${id}`, { method: 'PUT', cookie: owner.cookie, body: { ...draft, kind: 'available', revision: mine.posts[0].revision }, expected: 409 });
await request(`/posts/${id}`, { method: 'PUT', cookie: owner.cookie, body: { ...draft, description: 'Edited safely', revision: mine.posts[0].revision } });
const edited = (await request(`/state?postId=${id}`, { cookie: owner.cookie })).data.posts[0];
assert.equal(edited.createdAt, first.createdAt); assert.deepEqual(edited.interested,[applicant.id]); checks++;
await request(`/posts/${id}`, { method: 'DELETE', cookie: owner.cookie, expected: 204 });
assert.equal((await request(`/state?postId=${id}`, { cookie: owner.cookie })).data.posts.length, 0); checks++;
await request(`/posts/${id}/contacts/${applicant.id}`, { cookie: owner.cookie, expected: 404 });
await request('/auth/logout', { method: 'POST', cookie: owner.cookie, expected: 204 });
assert.equal((await request('/state', { cookie: owner.cookie })).data.email, ''); checks++;
console.log(`${checks} API checks passed: real codes, cookie sessions, profile, validation, ownership, private contacts, idempotency, concurrency, deletion and logout.`);
