/** Broad site categories; specialist tasks belong in the description. */
export const trades = [
  'Carpenter',
  'Builder',
  'Cabinet Maker',
  'Concreter',
  'Steel Fixer',
  'Bricklayer / Stonemason',
  'Electrician',
  'Plumber',
  'Air Conditioning / Refrigeration',
  'Roofer',
  'Waterproofer',
  'Plasterer / Renderer',
  'Painter',
  'Tiler',
  'Flooring Installer',
  'Glazier',
  'Welder / Boilermaker',
  'Scaffolder',
  'Rigger / Dogger',
  'Plant Operator',
  'Civil Construction Worker',
  'Demolition Worker',
  'Landscaper',
  'Labourer',
  'Other',
] as const;

const legacyTrades: Record<string, string> = {
  'Formwork Carpenter': 'Carpenter',
  Joiner: 'Carpenter',
  Shopfitter: 'Carpenter',
  'Cladding Installer': 'Carpenter',
  'Site Supervisor': 'Builder',
  'Stone Benchtop Installer': 'Cabinet Maker',
  'Concrete Finisher': 'Concreter',
  'Concrete Pump Operator': 'Concreter',
  'Concrete Cutter / Core Driller': 'Concreter',
  'Bricklayer / Blocklayer': 'Bricklayer / Stonemason',
  Stonemason: 'Bricklayer / Stonemason',
  'Solar Installer': 'Electrician',
  'Data / Telecommunications Cabler': 'Electrician',
  'Security Systems Installer': 'Electrician',
  'Electrical Linesworker': 'Electrician',
  Drainer: 'Plumber',
  Gasfitter: 'Plumber',
  'Roof Plumber': 'Plumber',
  'Civil Pipe Layer': 'Plumber',
  'Air Conditioning / Refrigeration Mechanic': 'Air Conditioning / Refrigeration',
  'Mechanical Services / HVAC Installer': 'Air Conditioning / Refrigeration',
  'Duct Installer': 'Air Conditioning / Refrigeration',
  'Metal Roofer': 'Roofer',
  'Roof Tiler': 'Roofer',
  'Caulker / Joint Sealer': 'Waterproofer',
  'Plasterer / Gyprocker': 'Plasterer / Renderer',
  'Solid Plasterer / Renderer': 'Plasterer / Renderer',
  'Ceiling / Partition Installer': 'Plasterer / Renderer',
  'Wall & Floor Tiler': 'Tiler',
  'Carpet Layer': 'Flooring Installer',
  'Window / Door Installer': 'Glazier',
  Welder: 'Welder / Boilermaker',
  Boilermaker: 'Welder / Boilermaker',
  'Structural Steel Erector': 'Welder / Boilermaker',
  Rigger: 'Rigger / Dogger',
  Dogger: 'Rigger / Dogger',
  'Earthmoving Plant Operator': 'Plant Operator',
  'Excavator Operator': 'Plant Operator',
  'Skid Steer Operator': 'Plant Operator',
  'Backhoe Operator': 'Plant Operator',
  'Bulldozer Operator': 'Plant Operator',
  'Grader Operator': 'Plant Operator',
  'Roller Operator': 'Plant Operator',
  'Dump Truck Operator': 'Plant Operator',
  'Crane Operator': 'Plant Operator',
  'Forklift Operator': 'Plant Operator',
  'Piling / Drilling Operator': 'Plant Operator',
  'Asphalt / Road Surfacing Worker': 'Civil Construction Worker',
  Paver: 'Landscaper',
  Fencer: 'Landscaper',
  'Retaining Wall Installer': 'Landscaper',
  'Irrigation Installer': 'Landscaper',
  'Trades Assistant': 'Labourer',
  'Construction Cleaner': 'Labourer',
  'Other Trade / Site Role': 'Other',
  'Lift Mechanic': 'Other',
  'Mechanical Fitter': 'Other',
  'Fire Sprinkler Fitter': 'Other',
  'Fire Protection Technician': 'Other',
  'Insulation Installer': 'Other',
  'Traffic Controller': 'Other',
  'Asbestos Removalist': 'Other',
  Surveyor: 'Other',
  'Pool Builder': 'Other',
};

export function normalizeTrade(value: string): string {
  if (trades.some((trade) => trade === value)) return value;
  return legacyTrades[value] ?? 'Other';
}
